ZMoec/Controllers/ZMRoleMaintenanceController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using ZMoec.Models;
using System.Collections.Generic;
using Microsoft.AspNet.Identity.EntityFramework;

namespace ZMoec.Controllers
{
    /// <summary>
    /// This controller is used to manage roles in the system
    /// </summary>
    [Authorize(Roles = "Administrator")]//This controller is only accessible by Administrator
    public class ZMRoleMaintenanceController : Controller
    {
        private ApplicationUserManager _userManager;
        ApplicationDbContext db = new ApplicationDbContext();

        /// <summary>
        /// Default Constructor
        /// </summary>
        public ZMRoleMaintenanceController()
        {
        }

        /// <summary>
        /// Instantiatin ApplicationUserManager class
        /// </summary>
        /// <param name="userManager"></param>
        public ZMRoleMaintenanceController(ApplicationUserManager userManager)
        {
            UserManager = userManager;

        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();//Getting ApplicationUserManager with Owin context. This is important to access some features like genereating reset password tokes etc.
            }
            private set
            {
                _userManager = value;
            }
        }

        /// <summary>
        /// Return list of Roles in the system
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {

            return View(db.Roles.OrderBy(a => a.Name).Select(a => a).ToList());
        }

        /// <summary>
        /// Creates new role
        /// </summary>
        /// <param name="form">Form collection that contains new role name</param>
        /// <returns>View along with errors or redirects to index if successfull</returns>
        [HttpPost]
        public ActionResult Create(FormCollection form)
        {
            try
            {
                if (form["RoleName"].ToString().Trim() != "")
                {
                    IdentityRole model = new IdentityRole() { Name = form["RoleName"].ToString().Trim() };
                    if (db.Roles.Where(a => a.Name.Contains(model.Name)).Count() > 0)//Checking if role already exists
                    {

                        TempData["message"] = "Role - " + model.Name + " already exists";
                        TempData["messagetype"] = "danger";
                        return RedirectToAction("Index");
                    }
                    db.Roles.Add(model);
                    db.SaveChanges();
                    TempData["message"] = "Role - " + model.Name + " created successfully";
                    TempData["messagetype"] = "success";
                }
                else
                {
                    TempData["message"] = "Please enter Role";
                    TempData["messagetype"] = "danger";
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["message"] = "Error creating Role: " + ex.GetBaseException().Message;
                TempData["messageType"] = "danger";
                return RedirectToAction("Index");
            }
        }



        /// <summary>
        /// Deletes the role directly if no users are associated with that role. Else will display list of users associated with the role and take confirmation from Admin to remove users from role
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Delete(string id)
        {
            List<UserViewModel> list = new List<UserViewModel>();
            IdentityRole role = db.Roles.Find(id);
            ViewBag.roleName = role.Name;
            if (role.Name == "Administrator")
            {
                TempData["message"] = "Administrator role cannot be deleted";
                TempData["messageType"] = "danger";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["message"] = "You have to remove all the user from " + role.Name + " role before deleteing it";
                TempData["messageType"] = "info";
                var users = db.Users.Select(a => a);

                foreach (var a in users)
                {
                    UserViewModel tempModel = new UserViewModel();
                    if (UserManager.IsInRole(a.Id, role.Name))
                    {
                        tempModel.Email = a.Email;
                        tempModel.IsLockedOut = a.LockoutEnabled;
                        tempModel.UserId = a.Id;
                        tempModel.UserName = a.UserName;
                        list.Add(tempModel);
                    }

                }
            }
            if (list.Count() == 0)//if no users is associated with the role then it will delete the role directly
            {
                FormCollection form = new FormCollection();
                form["removeAllUsersFromRole"] = "true";
                form["roleName"] = ViewBag.roleName;
                Delete(form);
                return RedirectToAction("Index");
            }
            return View(list);
        }

        /// <summary>
        /// Removes all the users from the role and then deletes the role
        /// </summary>
        /// <param name="form">Form collection containing Admin confimation for removing users from role and then delete the role</param>
        /// <returns>Redirects to Index page upon successfull deletion</returns>
        [HttpPost]
        public ActionResult Delete(FormCollection form)
        {
            try
            {
                List<UserViewModel> list = new List<UserViewModel>();
                bool removeAllUsersFromRole = form["removeAllUsersFromRole"].ToString().Contains("true") ? true : false;
                string roleName = form["roleName"].ToString();
                var users = db.Users.Select(a => a);
                foreach (var a in users)
                {
                    UserViewModel tempModel = new UserViewModel();
                    if (UserManager.IsInRole(a.Id, roleName))
                    {
                        tempModel.Email = a.Email;
                        tempModel.IsLockedOut = a.LockoutEnabled;
                        tempModel.UserId = a.Id;
                        tempModel.UserName = a.UserName;
                        list.Add(tempModel);
                    }

                }
                ViewBag.roleName = roleName;
                if (roleName == "Administrator")//cannot delete administrator
                {
                    TempData["message"] = "You cannot delete Administrator role";
                    TempData["messageType"] = "danger";
                    return View(list);
                }


                if (removeAllUsersFromRole)//if checkedbox is checked
                {
                    var query = UserManager.Users.Select(a => a).ToList();
                    foreach (var a in query)
                    {
                        UserManager.RemoveFromRole(a.Id, roleName);
                    }
                    IdentityRole role = db.Roles.Where(a => a.Name == roleName).Select(a => a).SingleOrDefault();
                    db.Roles.Remove(role);
                    db.SaveChanges();
                    TempData["message"] = "Role - " + roleName + " deleted successfully";
                    TempData["messageType"] = "success";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["message"] = "You have to remove all the users from this role before deleting it";
                    TempData["messageType"] = "danger";

                }

                return View(list);


            }
            catch (Exception ex)
            {
                TempData["message"] = "Error deleting role:" + ex.GetBaseException().Message;
                TempData["messageType"] = "danger";
                return View();
            }
        }
        /// <summary>
        /// Displays all the users associated with the role
        /// </summary>
        /// <param name="id">role id</param>
        /// <returns>View along with list of users associated with the role</returns>
        public ActionResult Users(string id)
        {
            List<UserViewModel> usersInRole = new List<UserViewModel>();
            List<UserViewModel> usersNotInRole = new List<UserViewModel>();
            IdentityRole role = db.Roles.Find(id);
            ViewBag.currentUserRoles = UserManager.GetRoles(User.Identity.GetUserId()).ToList();
            ViewBag.roleName = role.Name;
            ViewBag.currentUserId = User.Identity.GetUserId();
            var users = db.Users.Select(a => a);
            foreach (var a in users)
            {
                UserViewModel tempModel = new UserViewModel();
                tempModel.Email = a.Email;
                tempModel.IsLockedOut = a.LockoutEnabled;
                tempModel.UserId = a.Id;
                tempModel.UserName = a.UserName;
                tempModel.Roles = UserManager.GetRoles(a.Id).ToList();
                if (UserManager.IsInRole(a.Id, role.Name))
                {

                    usersInRole.Add(tempModel);
                }
                else
                {
                    usersNotInRole.Add(tempModel);
                }

            }
            ViewBag.userId = new SelectList(usersNotInRole, "UserId", "Email");
            return View(usersInRole);
        }

ZMoec/Views/ZMRoleMaintenance/Delete.cshtml
@model List<ZMoec.Models.UserViewModel>
@{
    ViewBag.Title = "Delete Role - " + ViewBag.roleName;
    using (Html.BeginForm(new { @class = "form-inline" }))
    {
        @Html.AntiForgeryToken()
        @Html.Hidden("roleName", (object)ViewBag.roleName)
        <div class="row">
            <div class="alert alert-warning">
                <h2>@ViewBag.Title</h2>
                <span>Remove all users from @ViewBag.roleName</span>
                @Html.CheckBox("removeAllUsersFromRole", (Model.Count() > 0) ? false : true)
                <button type="submit" class="btn btn-primary pull-right" value="Delete"><i class="glyphicon glyphicon-trash"></i> Delete</button>
            </div>
        </div>

    }
}
<h4>Users as a @ViewBag.roleName</h4>
<table class="table table-striped table-bordered">
    <tr>

        <th>
            Username
        </th>

        <th>
            Email
        </th>




    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>



        </tr>
    }

</table>

ZMoec/Views/ZMRoleMaintenance/Index.cshtml
@model List<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Role List";
}

<h2>@ViewBag.Title</h2>
<div class="row text-center">
    @using (Html.BeginForm("Create", "ZMRoleMaintenance", FormMethod.Post, new { @class = "form-inline" }))
    {
        <div class="form-group">

            <input type="text" class="form-control" id="RoleName" name="RoleName" placeholder="Role Name">
        </div>
        <button type="submit" class="btn btn-default">Create</button>
    }
</div>
<div class="row top-buffer">
    <table class="table table-striped table-bordered">
        <tr>
            <th>
                Role Name
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @if (item.Name != "Administrator")
                    {

                        @Html.ActionLink("Delete", "Delete", new { id = item.Id }) <span>|</span>


                    }
                     @Html.ActionLink("Manage Users", "Users", new { id = item.Id })

                </td>
            </tr>
        }

    </table>

</div>

ZMoec/Views/ZMRoleMaintenance/Users.cshtml
@model List<ZMoec.Models.UserViewModel>
@{
    ViewBag.Title = "Users as a " + ViewBag.roleName;
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("AddUserToRole", "ZMRoleMaintenance", FormMethod.Post, new { @class = "form", style = "display:inline;" }))
{
    @Html.Hidden("roleName", (object)ViewBag.roleName)
    <span>Users:</span>
    @Html.DropDownList("userId", null, htmlAttributes: new { @class = "form-control", style = "display:inline;" })
    <button type="submit" style="display:inline;" class="btn btn-primary"><i class="glyphicon-plus"></i> Add to @ViewBag.roleName</button>
}
<table class="table table-bordered table-striped top-buffer">
    <tr>
        <th>
            Username
        </th>

        <th>
            Email
        </th>
        <th>
            IsLockedOut
        </th>
        <th>
            Is Authorized Locally
        </th>


        <th></th>
    </tr>
    @if (Model.Count() > 0)
    {
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsLockedOut)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsAuthorizedLocally)
                </td>
                <td>
                    @{

            if (!(ViewBag.currentUserRoles.Contains(ViewBag.roleName) && item.UserId == ViewBag.currentUserId))
            {
                @Html.ActionLink("Remove from Role", "RemoveUserFromRole", new { id = item.UserId, roleName = ViewBag.roleName })
            }
            else
            {
                <span>You cannot remove yourself from role</span>
            }




                    }

                </td>


            </tr>
        }
    }
    else
    {
        <tr><td colspan="4" style="text-align:center;">No data to display</td></tr>
    }


</table>
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ZMoec/Views/ZMRoleMaintenance/_Create.cshtml
@model  Microsoft.AspNet.Identity.EntityFramework.IdentityRole

@using (Html.BeginForm("Create","ZMRoleMaintenance",FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Role</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}